name: Build CTLGUI Executable

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Create and activate environment
      run: |
        conda create --name build-env python=3.9 pillow rdkit -c conda-forge --yes
        conda activate build-env

    - name: Install dependencies
      run: |
        conda activate build-env
        pip install pyinstaller

    - name: Print working directory and list files
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing files in lib/media:"
        ls -la ./lib/media

    - name: Check icon file permissions
      run: |
        if [ ! -r "./lib/media/nctl.ico" ]; then
          echo "Icon file is not readable."
          exit 1
        fi

    - name: Build executable
      run: |
        conda activate build-env
        pyinstaller --onefile --windowed --icon=nctl.ico --exclude-module tkinter.test --exclude-module unittest --exclude-module xml.parsers.expat ctlgui.py

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: CTLGUI-Executable
        path: dist/ctlgui.exe
