name: Build CTLGUI Executable

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv build-env
        build-env\Scripts\activate
        python -m pip install --upgrade pip wheel
        pip install rdkit

    - name: Build executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: ctlgui.py
        windows-icon-from-ico: lib/media/nctl.ico
        enable-plugins: tk-inter

    - name: List build directory
      run: dir ctlgui.dist

    - name: Check build directory contents
      run: |
        echo "Checking contents of ctlgui.dist"
        dir ctlgui.dist

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: CTLGUI-Executable
        path: ctlgui.dist/**
        if-no-files-found: warn
        include-hidden-files: false
      env:
        pythonLocation: C:\hostedtoolcache\windows\Python\3.9.13\x64
        PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.9.13\x64/lib/pkgconfig
        Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
        Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
        Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
        NUITKA_CACHE_DIR: D:\a\_actions\Nuitka\Nuitka-Action\main/nuitka/cache
        PYTHON_VERSION: 3.9
