name: Build CTLGUI Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Create and activate environment
      run: |
        conda create --name build-env python=3.9 pillow rdkit -c conda-forge --yes
        conda activate build-env

    - name: Install dependencies
      run: |
        conda activate build-env
        pip install pyinstaller

    - name: Build executable
      run: |
        conda activate build-env
        pyinstaller --onefile --windowed `
          --icon=nctl.ico `
          --exclude-module tkinter.test `
          --exclude-module unittest `
          --exclude-module xml.parsers.expat `
          ctlgui.py


    - name: Compress executable with UPX
      run: |
        conda activate build-env
        curl -L https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip -o upx.zip
        tar -xf upx.zip
        ./upx-4.0.2-win64/upx dist/ctlgui.exe

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: CTLGUI-Executable
        path: dist/ctlgui.exe
