name: Build CTLGUI Executable

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv build-env
        build-env\Scripts\activate
        python -m pip install --upgrade pip wheel
        pip install rdkit

    - name: Build executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: ctlgui.py
        windows-icon-from-ico: lib/media/nctl.ico
        enable-plugins: tk-inter

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: CTLGUI-Executable
        path: ctlgui.dist
