name: Build CTLGUI Executable

on:
  push:
    branches:
      - main
    # Trigger the workflow only when Python files are changed
    paths:
      - '**/*.py'  # Monitor all Python files in the repository
  pull_request:
    # Trigger on pull requests but only for Python files
    paths:
      - '**/*.py'  # Monitor all Python files in the repository
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Create and activate environment
      run: |
        conda create --name build-env python=3.9 pillow rdkit -c conda-forge --yes
        conda activate build-env

    - name: Install dependencies
      run: |
        conda activate build-env
        pip install pyinstaller

    - name: Build executable
      run: |
        conda activate build-env
        pyinstaller --onefile --windowed --icon=./lib/media/nctl.ico --exclude-module tkinter.test --exclude-module unittest --exclude-module xml.parsers.expat ctlgui.py

    # Skip UPX compression
    - name: Skip UPX compression (if UPX fails)
      run: echo "Skipping UPX compression due to errors."
    
    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: CTLGUI-Executable
        path: dist/ctlgui.exe
