name: Release CTLGUI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv build-env
        build-env\Scripts\activate
        python -m pip install --upgrade pip wheel
        pip install rdkit

    - name: Build executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: ctlgui.py
        windows-icon-from-ico: lib/media/nctl.ico
        enable-plugins: tk-inter
      env:
        NUITKA_OUTPUT_DIR: build/ctlgui.dist

    - name: List build directory
      run: dir ./build

    - name: Check build directory contents
      run: |
        echo "Checking contents of ctlgui.dist"
        dir ./build/ctlgui.dist

    - name: Package executable and lib folder
      run: |
        mkdir build/ctlgui.dist/lib
        cp -r lib/* build/ctlgui.dist/lib/
        cd build/ctlgui.dist
        Compress-Archive -Path ctlgui.exe, lib, *.dll, *.pyd, *.so, *.dylib -DestinationPath Chem2Line-${{ github.event.inputs.tag_name }}-Windows-x86_64.zip

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: CTLGUI-Executable
        path: build/ctlgui.dist/Chem2Line-${{ github.event.inputs.tag_name }}-Windows-x86_64.zip
        if-no-files-found: warn
        include-hidden-files: false

    - name: Generate Release Notes
      id: generate_release_notes
      run: |
        echo "## What's New?" > release_notes.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD >> release_notes.md

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: ${{ github.event.inputs.release_name }}
        body_path: release_notes.md
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/ctlgui.dist/Chem2Line-${{ github.event.inputs.tag_name }}-Windows-x86_64.zip
        asset_name: Chem2Line-${{ github.event.inputs.tag_name }}-Windows-x86_64.zip
        asset_content_type: application/zip
